import { useState } from "react";
import Image from "next/image";
import Link from "next/link";

import styles from "styles/Home.module.css";
import Button from "components/Button";
import granny from "src/assets/granny.jpg";
import Layout from "components/Layout";

export default function Home() {
  console.log(process.env.CUSTOM_KEY);
  const [isPwdShown, setIsPwdShown] = useState(false);
  const onSubmit = (e) => {
    e.preventDefault();
    const userData = {
      email: "mail@mail.com",
      role: "admin",
      token:
        "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c",
    };
    // localStorage.setItem("user-info", JSON.stringify(userData));
    // this.props.navigate("/");
  };
  return (
    <Layout title="Register">
      {/* <Head>
        <title>Fluffy News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <main className={styles.container}>
        <aside className={styles["side-content"]}>
          {/* <img
            className={styles["side-image"]}
            src="/granny.jpg"
            alt="granny-read-book"
          /> */}
          <Image
            src={granny}
            alt="granny-read-book"
            fill
            quality={1}
            priority
            // placeholder="blur"
          />
        </aside>
        <section className={styles["form-content"]}>
          <section className={styles["register-form"]} id="register">
            <h1>Sign Up</h1>
            <form className={styles["full-width"]}>
              <div className={styles["input-div"]}>
                <label>Email Address:</label>
                <input type="text" placeholder="Enter your email address" />
              </div>
              <div className={styles["input-div"]}>
                <label>Password:</label>
                <input
                  type={isPwdShown ? "text" : "password"}
                  placeholder="Enter your password"
                />
                <span>show password</span>
                <input
                  className={styles["show-pwd"]}
                  type="checkbox"
                  defaultChecked={false}
                  onChange={() => {
                    // console.log("triggered");
                    setIsPwdShown(!isPwdShown);
                  }}
                />
              </div>
              <div className={styles["input-div"]}>
                <label>Phone Number:</label>
                <input type="tel" placeholder="Enter your phone number" />
              </div>
              <Button text="Sign Up" variant="primary" onClick={onSubmit} />
            </form>
          </section>
          <section
            className={`${styles["other-content"]} ${styles["flex-center"]}`}
          >
            <p className={styles["signup-text"]}>OR SIGN UP WITH</p>
            <section className={styles["oauth-button"]}>
              {/* <img className={styles.cursor} src={google} alt="google" />
                <img className={styles.cursor} src={fb} alt="facebook" />
                <img className={styles.cursor} src={twitter} alt="twitter" /> */}
            </section>
            <section
              className={`${styles["login-nav"]} ${styles["flex-center"]} ${styles["full-width"]}`}
            >
              <p>Already have an account</p>
              <Link href={"/products/2"} className={styles.btn}>
                <Button text="Login Here" variant="secondary" />
              </Link>
            </section>
            <section className={styles["home-nav"]}>
              <p>Back To Home page</p>
            </section>
          </section>
        </section>
      </main>
      <footer className={styles["container"]}>
        <aside className={styles["app-info"]}>
          <p>Why News Today</p>
          <p>Be an Author</p>
          <p>Community</p>
          <p>FAQ</p>
        </aside>
        <aside className={styles["address"]}>
          <p>News Today</p>
          <p>
            Jenderal Sudirman Street No. 23
            <br />
            Jakarta, Indonesia
          </p>
          <p>(621)989898934</p>
          <p>newstoday@gmail.com</p>
        </aside>
      </footer>
    </Layout>
  );
}
